#!/usr/bin/env python3
"""Generate BATTLE_CARD.md from battlecard.yml.

The card is the one artifact used while a customer is talking, so it must stay
short and must never drift from the naming and citation rules. Generating it
means a Databricks rename is a one-string edit plus a rebuild, not a rewrite.

    python3 scripts/build_battlecard.py           # regenerate the card
    python3 scripts/build_battlecard.py --check   # fail if it is out of date

Long-form material belongs in docs/competitive_reference.md, not here.
"""
from __future__ import annotations

import argparse
import pathlib
import sys

try:
    import yaml
except ImportError:  # pragma: no cover
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    raise SystemExit(1)

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from build_citations import expected_text, load_claims  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "battlecard.yml"
CARD = ROOT / "BATTLE_CARD.md"
MAX_BODY_LINES = 110  # a card that outgrows this is a reference doc wearing a hat


def render(spec: dict) -> str:
    o = []
    o.append("---")
    for k in ("version", "last_verified", "expires", "owner", "reverify"):
        if spec.get(k):
            o.append(f"{k}: {spec[k]}")
    o.append("---")
    o.append("")
    o.append("<!-- GENERATED from battlecard.yml by scripts/build_battlecard.py.")
    o.append("     Do not edit this file directly; edit battlecard.yml and rebuild. -->")
    o.append("")
    o.append("# dbt + Databricks - Field Battle Card")
    o.append("")
    o.append(
        "One page, for use during a call. Deep dives: "
        "`docs/competitive_reference.md`. Naming: `NAMING.md`. "
        "Sources: `sources.yml`."
    )
    o.append("")
    o.append("## Positioning")
    o.append("")
    o.append(spec["positioning"].strip())
    o.append("")
    o.append("> " + spec["opening_question"].strip().replace("\n", "\n> "))
    o.append("")

    o.append("## Fast facts")
    o.append("")
    for f in spec["fast_facts"]:
        o.append(f"- {f}")
    o.append("")

    o.append("## Objections")
    o.append("")
    o.append("| They say | Response | Business value |")
    o.append("|---|---|---|")
    for ob in spec["objections"]:
        o.append(f"| \"{ob['say']}\" | {ob['response']} | {ob['value']} |")
    o.append("")

    o.append("## Do not say these - they get corrected live")
    o.append("")
    o.append("| Don't say | Say instead |")
    o.append("|---|---|")
    for d in spec["do_not_say"]:
        dont = d["dont"]
        if not dont.startswith("`"):
            dont = f'"{dont}"'
        o.append(f"| {dont} | {d['instead']} |")
    o.append("")

    if spec.get("databricks_wins"):
        o.append("## Where Databricks genuinely wins - concede these")
        o.append("")
        for w in spec["databricks_wins"]:
            o.append(f"- {w}")
        o.append("")

    o.append("## Discovery questions")
    o.append("")
    for q in spec["discovery_questions"]:
        o.append(f'- "{q}"')
    o.append("")

    o.append("## Guardrails")
    o.append("")
    for g in spec["guardrails"]:
        o.append(f"- {g}")
    o.append("")
    return "\n".join(o).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    spec = yaml.safe_load(SPEC.read_text(encoding="utf-8"))
    body = render(spec)

    n = len(body.splitlines())
    if n > MAX_BODY_LINES:
        print(
            f"battlecard.yml renders to {n} lines (limit {MAX_BODY_LINES}). "
            "Move something into docs/competitive_reference.md."
        )
        return 1

    final = expected_text(body, load_claims())

    if args.check:
        if not CARD.exists() or CARD.read_text(encoding="utf-8") != final:
            print("BATTLE_CARD.md is out of date - run scripts/build_battlecard.py")
            return 1
        print(f"BATTLE_CARD.md is current ({n} body lines)")
        return 0

    CARD.write_text(final, encoding="utf-8")
    print(f"wrote BATTLE_CARD.md ({n} body lines, limit {MAX_BODY_LINES})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
